# Generated by Django 3.1.2 on 2020-10-15 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('comment', models.TextField()),
                ('name', models.CharField(default='none', max_length=60)),
                ('post', models.CharField(default='none', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=60)),
                ('email', models.CharField(default='none', max_length=60)),
                ('phone', models.CharField(default='none', max_length=60)),
                ('subject', models.CharField(default='none', max_length=150)),
                ('message', models.CharField(default='none', max_length=60)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('title', models.CharField(default='none', max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=60)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('sqft', models.CharField(default='none', max_length=60)),
                ('location', models.CharField(default='none', max_length=60)),
                ('room', models.IntegerField()),
                ('shower', models.IntegerField()),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('footer', models.CharField(blank=True, max_length=50)),
                ('newsletter', models.CharField(blank=True, max_length=50)),
                ('project', models.CharField(blank=True, max_length=50)),
                ('years', models.CharField(blank=True, max_length=50)),
                ('professionals', models.CharField(blank=True, max_length=50)),
                ('machines', models.CharField(blank=True, max_length=50)),
                ('icon', models.ImageField(blank=True, upload_to='images')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('aboutheader', models.TextField(blank=True, max_length=500)),
                ('aboutus', models.TextField(blank=True, max_length=500)),
                ('mission', models.TextField(blank=True, max_length=500)),
                ('vision', models.TextField(blank=True, max_length=500)),
                ('values', models.TextField(blank=True, max_length=500)),
                ('whoweare', models.TextField(blank=True, max_length=500)),
                ('whatwedo', models.TextField(blank=True, max_length=500)),
                ('contact', models.TextField(blank=True, max_length=500)),
                ('references', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
